### ISSUE TITLE
Why I can't view event details without signing in?

### ISSUE THREAD

**Issue by joy-dey** [unknown009d/eventmanagement#2]
As a user I want to view the details of the event and I should be allowed to view the details without requiring signing in or sign up

**Comment by unknown009d** [comment]
Alright mate. Thanks for letting me know, working on it.

**Comment by unknown009d** [comment]
Hey @joy-dey I have added this functionality, feel free to have a look into it.
[Link for deployment regarding this issue](https://eventmanagement-git-cant-view-event-detail-f6bf29-evms-projects.vercel.app/ )
Here's a development link for the following issue. Feel free to give suggestions if needed.

**Comment by joy-dey** [comment]
Looks good.
